name: CDK Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: eu-west-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::509616620028:role/GitHubActionsECRPushRole
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-session

      - name: Set up Python and Node
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --only main
          npm install -g aws-cdk

      - name: Debug OIDC Token
        run: |
          echo "OIDC Token:"
          curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL"

      - name: Deploy CDK
        run: |
          cdk deploy --require-approval never --app "poetry run python3 infrastructure/cdk/app.py"
