name: CDK Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  deploy:
    if: github.event_name != 'workflow_dispatch'  # Skip deploy if manually triggered
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: eu-west-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::509616620028:role/GitHubActionsECRPushRole
          aws-region: eu-west-2
          role-session-name: github-actions-session

      - name: Set up Python and Node
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --only main
          npm install -g aws-cdk

      - name: Deploy CDK
        run: |
          cdk deploy --require-approval never --app "poetry run python3 infrastructure/cdk/app.py"

  destroy:
    if: github.event_name == 'workflow_dispatch'  # Only run if manually triggered
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: eu-west-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::509616620028:role/GitHubActionsECRPushRole
          aws-region: eu-west-2

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Destroy CDK stack
        run: cdk destroy --force --app "poetry run python3 infrastructure/cdk/app.py"
